name: Check new links against deployment
on:
  - deployment_status
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    continue-on-error: true
    if:
      github.event.deployment.ref != 'main' &&
      github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: iterative/setup-cml@v1
      - name: Run Link Check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: check
        run: |
          set +e
          body="<h1 id=\"link-check\">Link Check Report</h1>

          $(
            npx repo-link-check \
            -d -c config/link-check/config.yml \
            -r ${{ github.event.deployment.payload.web_url }}
          )"
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo $body > report.md
          cml-send-comment report.md
